### ISSUE TITLE
Chyba

### ISSUE THREAD

**Issue by kubqqo** [jsfraz/sfgame-albumer#1]
čau requirements jsem nainstaloval hru mam spustenou ale pise to tento error.
![image](https://github.com/jsfraz/sfgame-albumer/assets/160538504/5d404ac4-b769-4a24-be6d-1a2ad6b9cefe)
kdyztak odpovez na tento koment discordem tam bude lepsi komunikace 👍

**Comment by jsfraz** [comment]
Chybu jsem [opravil](https://github.com/jsfraz/sfgame-albumer/commit/b7bb5a053719827c9776fbadb59fb865cfc036f6). Problém byl v detekci okna. Kdyby byly ještě problémy napiš, nick: jsfrz.
